In [1]:
# pip install fastai==1.0.61
from enum import Enum
import os
import fastai
from musicautobot.numpy_encode import *
from musicautobot.config import *
from musicautobot.music_transformer import *
from musicautobot.multitask_transformer import *
from musicautobot.utils import midifile


In [17]:

#item = MusicItem.from_file('wii.mid', MusicVocab.create())
#print(item.to_text())
#print(len(item))
#print(item.to_tensor())
print(midi2npenc('wii.mid')) #throws warning
embedding = midi2idxenc('wii.mid', MusicVocab.create())
print(type(embedding))
print(midi2idxenc('wii.mid', MusicVocab.create()))
print(len(midi2idxenc('wii.mid', MusicVocab.create())))

[[66  2]
 [62  2]
 [47  2]
 [-1  4]
 ...
 [68  1]
 [64  1]
 [59  1]
 [49  1]]
<class 'numpy.ndarray'>
[  0   1  75 139 ...  68 138  58 138]
1616


In [13]:
path_list = []
path = "C:\\Users\\drago\\OneDrive\\Documents\\MOVE TO NEW PC\\College\\fall 2022\\FIRE\\maestro\\maestro-v3.0.0"
for i in os.listdir(path):
    if i[0] == "2":
        for j in os.listdir(path + '\\' + i):
            newpath = path + "\\" + i + '\\' + j
            print(newpath)
            path_list.append(newpath)

C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_05_Track05_wav.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_06_Track06_wav.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_08_Track08_wav.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_10_Track10_wav.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_05_R1_2004_01_ORIG_MID--AUDIO_05_R1_2004_02_Track02_wav.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestr

C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2017\MIDI-Unprocessed_081_PIANO081_MID--AUDIO-split_07-09-17_Piano-e_2_-02_wav--4.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2017\MIDI-Unprocessed_082_PIANO082_MID--AUDIO-split_07-09-17_Piano-e_2_-04_wav--1.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2017\MIDI-Unprocessed_082_PIANO082_MID--AUDIO-split_07-09-17_Piano-e_2_-04_wav--2.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2017\MIDI-Unprocessed_082_PIANO082_MID--AUDIO-split_07-09-17_Piano-e_2_-04_wav--3.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2017\MIDI-Unprocessed_083_PIANO083_MID--AUDIO-split_07-09-17_Piano-e_2_-06_wav--1.midi
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3

In [18]:
vocab = MusicVocab.create()
for i in path_list:
    print(i)
    enc = midi2idxenc(i, vocab)
    print(enc)
    print(len(enc))


C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_05_Track05_wav.midi
[  0   1   8 146 ...  68 139  64 138]
25954
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_06_Track06_wav.midi
[  0   1   8 145 ...  64 148  61 148]
3988
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_08_Track08_wav.midi
[  0   1   8 145 ...  95 138  86 138]
7858
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestro-v3.0.0\2004\MIDI-Unprocessed_SMF_02_R1_2004_01-05_ORIG_MID--AUDIO_02_R1_2004_10_Track10_wav.midi
[  0   1   8 145 ...  52 142  45 142]
16916
C:\Users\drago\OneDrive\Documents\MOVE TO NEW PC\College\fall 2022\FIRE\maestro\maestr

KeyboardInterrupt: 

1276